" quit when a syntax file was already loaded
if exists("b:current_syntax")
  finish
endif

if !exists('main_syntax')
  let main_syntax = 'octo'
endif

unlet! b:current_syntax

call matchadd('Conceal', ':thinking:', 10, -1, {'conceal':'🤔'})
call matchadd('Conceal', ':laughing:', 10, -1, {'conceal':'😆'})
call matchadd('Conceal', ':shrug:', 10, -1, {'conceal':'🤷'})
call matchadd('Conceal', ':man_shrugging:', 10, -1, {'conceal':'🤷'})
call matchadd('Conceal', ':cowboy_hat_face:', 10, -1, {'conceal':'🤠'})
call matchadd('Conceal', ':blush:', 10, -1, {'conceal':'😊'})
call matchadd('Conceal', ':smiley:', 10, -1, {'conceal':'😃'})
call matchadd('Conceal', ':relaxed:', 10, -1, {'conceal':'☺️'})
call matchadd('Conceal', ':smirk:', 10, -1, {'conceal':'😏'})
call matchadd('Conceal', ':heart_eyes:', 10, -1, {'conceal':'😍'})
call matchadd('Conceal', ':kissing_heart:', 10, -1, {'conceal':'😘'})
call matchadd('Conceal', ':kissing_closed_eyes:', 10, -1, {'conceal':'😚'})
call matchadd('Conceal', ':flushed:', 10, -1, {'conceal':'😳'})
call matchadd('Conceal', ':relieved:', 10, -1, {'conceal':'😌'})
call matchadd('Conceal', ':satisfied:', 10, -1, {'conceal':'😆'})
call matchadd('Conceal', ':grin:', 10, -1, {'conceal':'😁'})
call matchadd('Conceal', ':wink:', 10, -1, {'conceal':'😉'})
call matchadd('Conceal', ':stuck_out_tongue_winking_eye:', 10, -1, {'conceal':'😜'})
call matchadd('Conceal', ':stuck_out_tongue_closed_eyes:', 10, -1, {'conceal':'😝'})
call matchadd('Conceal', ':grinning:', 10, -1, {'conceal':'😀'})
call matchadd('Conceal', ':kissing:', 10, -1, {'conceal':'😗'})
call matchadd('Conceal', ':kissing_smiling_eyes:', 10, -1, {'conceal':'😙'})
call matchadd('Conceal', ':stuck_out_tongue:', 10, -1, {'conceal':'😛'})
call matchadd('Conceal', ':sleeping:', 10, -1, {'conceal':'😴'})
call matchadd('Conceal', ':worried:', 10, -1, {'conceal':'😟'})
call matchadd('Conceal', ':frowning:', 10, -1, {'conceal':'😦'})
call matchadd('Conceal', ':anguished:', 10, -1, {'conceal':'😧'})
call matchadd('Conceal', ':open_mouth:', 10, -1, {'conceal':'😮'})
call matchadd('Conceal', ':grimacing:', 10, -1, {'conceal':'😬'})
call matchadd('Conceal', ':confused:', 10, -1, {'conceal':'😕'})
call matchadd('Conceal', ':hushed:', 10, -1, {'conceal':'😯'})
call matchadd('Conceal', ':expressionless:', 10, -1, {'conceal':'😑'})
call matchadd('Conceal', ':unamused:', 10, -1, {'conceal':'😒'})
call matchadd('Conceal', ':sweat_smile:', 10, -1, {'conceal':'😅'})
call matchadd('Conceal', ':sweat:', 10, -1, {'conceal':'😓'})
call matchadd('Conceal', ':disappointed_relieved:', 10, -1, {'conceal':'😥'})
call matchadd('Conceal', ':weary:', 10, -1, {'conceal':'😩'})
call matchadd('Conceal', ':pensive:', 10, -1, {'conceal':'😔'})
call matchadd('Conceal', ':disappointed:', 10, -1, {'conceal':'😞'})
call matchadd('Conceal', ':confounded:', 10, -1, {'conceal':'😖'})
call matchadd('Conceal', ':fearful:', 10, -1, {'conceal':'😨'})
call matchadd('Conceal', ':cold_sweat:', 10, -1, {'conceal':'😰'})
call matchadd('Conceal', ':persevere:', 10, -1, {'conceal':'😣'})
call matchadd('Conceal', ':cry:', 10, -1, {'conceal':'😢'})
call matchadd('Conceal', ':sob:', 10, -1, {'conceal':'😭'})
call matchadd('Conceal', ':joy:', 10, -1, {'conceal':'😂'})
call matchadd('Conceal', ':astonished:', 10, -1, {'conceal':'😲'})
call matchadd('Conceal', ':scream:', 10, -1, {'conceal':'😱'})
call matchadd('Conceal', ':tired_face:', 10, -1, {'conceal':'😫'})
call matchadd('Conceal', ':angry:', 10, -1, {'conceal':'😠'})
call matchadd('Conceal', ':rage:', 10, -1, {'conceal':'😡'})
call matchadd('Conceal', ':triumph:', 10, -1, {'conceal':'😤'})
call matchadd('Conceal', ':sleepy:', 10, -1, {'conceal':'😪'})
call matchadd('Conceal', ':yum:', 10, -1, {'conceal':'😋'})
call matchadd('Conceal', ':mask:', 10, -1, {'conceal':'😷'})
call matchadd('Conceal', ':sunglasses:', 10, -1, {'conceal':'😎'})
call matchadd('Conceal', ':dizzy_face:', 10, -1, {'conceal':'😵'})
call matchadd('Conceal', ':imp:', 10, -1, {'conceal':'👿'})
call matchadd('Conceal', ':smiling_imp:', 10, -1, {'conceal':'😈'})
call matchadd('Conceal', ':neutral_face:', 10, -1, {'conceal':'😐'})
call matchadd('Conceal', ':no_mouth:', 10, -1, {'conceal':'😶'})
call matchadd('Conceal', ':innocent:', 10, -1, {'conceal':'😇'})
call matchadd('Conceal', ':alien:', 10, -1, {'conceal':'👽'})
call matchadd('Conceal', ':yellow_heart:', 10, -1, {'conceal':'💛'})
call matchadd('Conceal', ':blue_heart:', 10, -1, {'conceal':'💙'})
call matchadd('Conceal', ':purple_heart:', 10, -1, {'conceal':'💜'})
" call matchadd('Conceal', ':heart:', 10, -1, {'conceal':'❤️'})
call matchadd('Conceal', ':green_heart:', 10, -1, {'conceal':'💚'})
call matchadd('Conceal', ':broken_heart:', 10, -1, {'conceal':'💔'})
call matchadd('Conceal', ':heartbeat:', 10, -1, {'conceal':'💓'})
call matchadd('Conceal', ':heartpulse:', 10, -1, {'conceal':'💗'})
call matchadd('Conceal', ':two_hearts:', 10, -1, {'conceal':'💕'})
call matchadd('Conceal', ':revolving_hearts:', 10, -1, {'conceal':'💞'})
call matchadd('Conceal', ':cupid:', 10, -1, {'conceal':'💘'})
call matchadd('Conceal', ':sparkling_heart:', 10, -1, {'conceal':'💖'})
call matchadd('Conceal', ':sparkles:', 10, -1, {'conceal':'✨'})
" call matchadd('Conceal', ':star:', 10, -1, {'conceal':'⭐'})
call matchadd('Conceal', ':star2:', 10, -1, {'conceal':'🌟'})
call matchadd('Conceal', ':dizzy:', 10, -1, {'conceal':'💫'})
call matchadd('Conceal', ':boom:', 10, -1, {'conceal':'💥'})
call matchadd('Conceal', ':collision:', 10, -1, {'conceal':'💥'})
call matchadd('Conceal', ':anger:', 10, -1, {'conceal':'💢'})
call matchadd('Conceal', ':exclamation:', 10, -1, {'conceal':'❗'})
call matchadd('Conceal', ':question:', 10, -1, {'conceal':'❓'})
call matchadd('Conceal', ':grey_exclamation:', 10, -1, {'conceal':'❕'})
call matchadd('Conceal', ':grey_question:', 10, -1, {'conceal':'❔'})
call matchadd('Conceal', ':zzz:', 10, -1, {'conceal':'💤'})
call matchadd('Conceal', ':dash:', 10, -1, {'conceal':'💨'})
call matchadd('Conceal', ':sweat_drops:', 10, -1, {'conceal':'💦'})
call matchadd('Conceal', ':notes:', 10, -1, {'conceal':'🎶'})
call matchadd('Conceal', ':musical_note:', 10, -1, {'conceal':'🎵'})
call matchadd('Conceal', ':fire:', 10, -1, {'conceal':'🔥'})
call matchadd('Conceal', ':hankey:', 10, -1, {'conceal':'💩'})
call matchadd('Conceal', ':poop:', 10, -1, {'conceal':'💩'})
call matchadd('Conceal', ':shit:', 10, -1, {'conceal':'💩'})
call matchadd('Conceal', ':+1:', 10, -1, {'conceal':'👍'})
call matchadd('Conceal', ':thumbsup:', 10, -1, {'conceal':'👍'})
call matchadd('Conceal', ':-1:', 10, -1, {'conceal':'👎'})
call matchadd('Conceal', ':thumbsdown:', 10, -1, {'conceal':'👎'})
call matchadd('Conceal', ':ok_hand:', 10, -1, {'conceal':'👌'})
call matchadd('Conceal', ':punch:', 10, -1, {'conceal':'👊'})
call matchadd('Conceal', ':facepunch:', 10, -1, {'conceal':'👊'})
call matchadd('Conceal', ':fist:', 10, -1, {'conceal':'✊'})
" call matchadd('Conceal', ':v:', 10, -1, {'conceal':'✌️'})
call matchadd('Conceal', ':wave:', 10, -1, {'conceal':'👋'})
call matchadd('Conceal', ':hand:', 10, -1, {'conceal':'✋'})
call matchadd('Conceal', ':raised_hand:', 10, -1, {'conceal':'✋'})
call matchadd('Conceal', ':open_hands:', 10, -1, {'conceal':'👐'})
" call matchadd('Conceal', ':point_up:', 10, -1, {'conceal':'☝️'})
call matchadd('Conceal', ':point_down:', 10, -1, {'conceal':'👇'})
call matchadd('Conceal', ':point_left:', 10, -1, {'conceal':'👈'})
call matchadd('Conceal', ':point_right:', 10, -1, {'conceal':'👉'})
call matchadd('Conceal', ':raised_hands:', 10, -1, {'conceal':'🙌'})
call matchadd('Conceal', ':pray:', 10, -1, {'conceal':'🙏'})
call matchadd('Conceal', ':point_up_2:', 10, -1, {'conceal':'👆'})
call matchadd('Conceal', ':clap:', 10, -1, {'conceal':'👏'})
call matchadd('Conceal', ':muscle:', 10, -1, {'conceal':'💪'})
call matchadd('Conceal', ':metal:', 10, -1, {'conceal':'🤘'})
call matchadd('Conceal', ':fu:', 10, -1, {'conceal':'🖕'})
call matchadd('Conceal', ':walking:', 10, -1, {'conceal':'🚶'})
call matchadd('Conceal', ':runner:', 10, -1, {'conceal':'🏃'})
call matchadd('Conceal', ':running:', 10, -1, {'conceal':'🏃'})
call matchadd('Conceal', ':couple:', 10, -1, {'conceal':'👫'})
call matchadd('Conceal', ':family:', 10, -1, {'conceal':'👪'})
call matchadd('Conceal', ':two_men_holding_hands:', 10, -1, {'conceal':'👬'})
call matchadd('Conceal', ':two_women_holding_hands:', 10, -1, {'conceal':'👭'})
call matchadd('Conceal', ':dancer:', 10, -1, {'conceal':'💃'})
call matchadd('Conceal', ':dancers:', 10, -1, {'conceal':'👯'})
call matchadd('Conceal', ':ok_woman:', 10, -1, {'conceal':'🙆‍♀️'})
call matchadd('Conceal', ':no_good:', 10, -1, {'conceal':'🙅'})
call matchadd('Conceal', ':information_desk_person:', 10, -1, {'conceal':'💁'})
call matchadd('Conceal', ':raising_hand:', 10, -1, {'conceal':'🙋'})
call matchadd('Conceal', ':bride_with_veil:', 10, -1, {'conceal':'👰‍♀️'})
call matchadd('Conceal', ':bow:', 10, -1, {'conceal':'🙇'})
call matchadd('Conceal', ':couplekiss:', 10, -1, {'conceal':'💏'})
call matchadd('Conceal', ':couple_with_heart:', 10, -1, {'conceal':'💑'})
call matchadd('Conceal', ':massage:', 10, -1, {'conceal':'💆'})
call matchadd('Conceal', ':haircut:', 10, -1, {'conceal':'💇'})
call matchadd('Conceal', ':nail_care:', 10, -1, {'conceal':'💅'})
call matchadd('Conceal', ':boy:', 10, -1, {'conceal':'👦'})
call matchadd('Conceal', ':girl:', 10, -1, {'conceal':'👧'})
call matchadd('Conceal', ':woman:', 10, -1, {'conceal':'👩'})
call matchadd('Conceal', ':man:', 10, -1, {'conceal':'👨'})
call matchadd('Conceal', ':baby:', 10, -1, {'conceal':'👶'})
call matchadd('Conceal', ':older_woman:', 10, -1, {'conceal':'👵'})
call matchadd('Conceal', ':older_man:', 10, -1, {'conceal':'👴'})
call matchadd('Conceal', ':man_with_gua_pi_mao:', 10, -1, {'conceal':'👲'})
call matchadd('Conceal', ':man_with_turban:', 10, -1, {'conceal':'👳‍♂️'})
call matchadd('Conceal', ':construction_worker:', 10, -1, {'conceal':'👷'})
call matchadd('Conceal', ':cop:', 10, -1, {'conceal':'👮'})
call matchadd('Conceal', ':angel:', 10, -1, {'conceal':'👼'})
call matchadd('Conceal', ':princess:', 10, -1, {'conceal':'👸'})
call matchadd('Conceal', ':smiley_cat:', 10, -1, {'conceal':'😺'})
call matchadd('Conceal', ':smile_cat:', 10, -1, {'conceal':'😸'})
call matchadd('Conceal', ':heart_eyes_cat:', 10, -1, {'conceal':'😻'})
call matchadd('Conceal', ':kissing_cat:', 10, -1, {'conceal':'😽'})
call matchadd('Conceal', ':smirk_cat:', 10, -1, {'conceal':'😼'})
call matchadd('Conceal', ':scream_cat:', 10, -1, {'conceal':'🙀'})
call matchadd('Conceal', ':crying_cat_face:', 10, -1, {'conceal':'😿'})
call matchadd('Conceal', ':joy_cat:', 10, -1, {'conceal':'😹'})
call matchadd('Conceal', ':pouting_cat:', 10, -1, {'conceal':'😾'})
call matchadd('Conceal', ':japanese_ogre:', 10, -1, {'conceal':'👹'})
call matchadd('Conceal', ':japanese_goblin:', 10, -1, {'conceal':'👺'})
call matchadd('Conceal', ':see_no_evil:', 10, -1, {'conceal':'🙈'})
call matchadd('Conceal', ':hear_no_evil:', 10, -1, {'conceal':'🙉'})
call matchadd('Conceal', ':speak_no_evil:', 10, -1, {'conceal':'🙊'})
call matchadd('Conceal', ':guardsman:', 10, -1, {'conceal':'💂‍♂️'})
call matchadd('Conceal', ':skull:', 10, -1, {'conceal':'💀'})
call matchadd('Conceal', ':feet:', 10, -1, {'conceal':'🐾'})
call matchadd('Conceal', ':lips:', 10, -1, {'conceal':'👄'})
call matchadd('Conceal', ':kiss:', 10, -1, {'conceal':'💋'})
call matchadd('Conceal', ':droplet:', 10, -1, {'conceal':'💧'})
call matchadd('Conceal', ':ear:', 10, -1, {'conceal':'👂'})
call matchadd('Conceal', ':eyes:', 10, -1, {'conceal':'👀'})
call matchadd('Conceal', ':nose:', 10, -1, {'conceal':'👃'})
call matchadd('Conceal', ':tongue:', 10, -1, {'conceal':'👅'})
call matchadd('Conceal', ':love_letter:', 10, -1, {'conceal':'💌'})
call matchadd('Conceal', ':bust_in_silhouette:', 10, -1, {'conceal':'👤'})
call matchadd('Conceal', ':busts_in_silhouette:', 10, -1, {'conceal':'👥'})
call matchadd('Conceal', ':speech_balloon:', 10, -1, {'conceal':'💬'})
call matchadd('Conceal', ':thought_balloon:', 10, -1, {'conceal':'💭'})
call matchadd('Conceal', ':sunny:', 10, -1, {'conceal':'☀️'})
call matchadd('Conceal', ':umbrella:', 10, -1, {'conceal':'☔'})
" call matchadd('Conceal', ':cloud:', 10, -1, {'conceal':'☁️'})
" call matchadd('Conceal', ':snowflake:', 10, -1, {'conceal':'❄️'})
call matchadd('Conceal', ':snowman:', 10, -1, {'conceal':'⛄'})
call matchadd('Conceal', ':zap:', 10, -1, {'conceal':'⚡'})
call matchadd('Conceal', ':cyclone:', 10, -1, {'conceal':'🌀'})
call matchadd('Conceal', ':foggy:', 10, -1, {'conceal':'🌁'})
call matchadd('Conceal', ':ocean:', 10, -1, {'conceal':'🌊'})
call matchadd('Conceal', ':cat:', 10, -1, {'conceal':'🐱'})
call matchadd('Conceal', ':dog:', 10, -1, {'conceal':'🐶'})
call matchadd('Conceal', ':mouse:', 10, -1, {'conceal':'🐭'})
call matchadd('Conceal', ':hamster:', 10, -1, {'conceal':'🐹'})
call matchadd('Conceal', ':rabbit:', 10, -1, {'conceal':'🐰'})
call matchadd('Conceal', ':wolf:', 10, -1, {'conceal':'🐺'})
call matchadd('Conceal', ':frog:', 10, -1, {'conceal':'🐸'})
call matchadd('Conceal', ':tiger:', 10, -1, {'conceal':'🐯'})
call matchadd('Conceal', ':koala:', 10, -1, {'conceal':'🐨'})
call matchadd('Conceal', ':bear:', 10, -1, {'conceal':'🐻'})
call matchadd('Conceal', ':pig:', 10, -1, {'conceal':'🐷'})
call matchadd('Conceal', ':pig_nose:', 10, -1, {'conceal':'🐽'})
call matchadd('Conceal', ':cow:', 10, -1, {'conceal':'🐮'})
call matchadd('Conceal', ':boar:', 10, -1, {'conceal':'🐗'})
call matchadd('Conceal', ':monkey_face:', 10, -1, {'conceal':'🐵'})
call matchadd('Conceal', ':monkey:', 10, -1, {'conceal':'🐒'})
call matchadd('Conceal', ':horse:', 10, -1, {'conceal':'🐴'})
call matchadd('Conceal', ':racehorse:', 10, -1, {'conceal':'🐎'})
call matchadd('Conceal', ':camel:', 10, -1, {'conceal':'🐫'})
call matchadd('Conceal', ':sheep:', 10, -1, {'conceal':'🐑'})
call matchadd('Conceal', ':elephant:', 10, -1, {'conceal':'🐘'})
call matchadd('Conceal', ':panda_face:', 10, -1, {'conceal':'🐼'})
call matchadd('Conceal', ':snake:', 10, -1, {'conceal':'🐍'})
call matchadd('Conceal', ':bird:', 10, -1, {'conceal':'🐦'})
call matchadd('Conceal', ':baby_chick:', 10, -1, {'conceal':'🐤'})
call matchadd('Conceal', ':hatched_chick:', 10, -1, {'conceal':'🐥'})
call matchadd('Conceal', ':hatching_chick:', 10, -1, {'conceal':'🐣'})
call matchadd('Conceal', ':chicken:', 10, -1, {'conceal':'🐔'})
call matchadd('Conceal', ':penguin:', 10, -1, {'conceal':'🐧'})
call matchadd('Conceal', ':turtle:', 10, -1, {'conceal':'🐢'})
call matchadd('Conceal', ':bug:', 10, -1, {'conceal':'🐛'})
call matchadd('Conceal', ':honeybee:', 10, -1, {'conceal':'🐝'})
call matchadd('Conceal', ':ant:', 10, -1, {'conceal':'🐜'})
call matchadd('Conceal', ':beetle:', 10, -1, {'conceal':'🪲'})
call matchadd('Conceal', ':snail:', 10, -1, {'conceal':'🐌'})
call matchadd('Conceal', ':octopus:', 10, -1, {'conceal':'🐙'})
call matchadd('Conceal', ':tropical_fish:', 10, -1, {'conceal':'🐠'})
call matchadd('Conceal', ':fish:', 10, -1, {'conceal':'🐟'})
call matchadd('Conceal', ':whale:', 10, -1, {'conceal':'🐳'})
call matchadd('Conceal', ':whale2:', 10, -1, {'conceal':'🐋'})
call matchadd('Conceal', ':dolphin:', 10, -1, {'conceal':'🐬'})
call matchadd('Conceal', ':cow2:', 10, -1, {'conceal':'🐄'})
call matchadd('Conceal', ':ram:', 10, -1, {'conceal':'🐏'})
call matchadd('Conceal', ':rat:', 10, -1, {'conceal':'🐀'})
call matchadd('Conceal', ':water_buffalo:', 10, -1, {'conceal':'🐃'})
call matchadd('Conceal', ':tiger2:', 10, -1, {'conceal':'🐅'})
call matchadd('Conceal', ':rabbit2:', 10, -1, {'conceal':'🐇'})
call matchadd('Conceal', ':dragon:', 10, -1, {'conceal':'🐉'})
call matchadd('Conceal', ':goat:', 10, -1, {'conceal':'🐐'})
call matchadd('Conceal', ':rooster:', 10, -1, {'conceal':'🐓'})
call matchadd('Conceal', ':dog2:', 10, -1, {'conceal':'🐕'})
call matchadd('Conceal', ':pig2:', 10, -1, {'conceal':'🐖'})
call matchadd('Conceal', ':mouse2:', 10, -1, {'conceal':'🐁'})
call matchadd('Conceal', ':ox:', 10, -1, {'conceal':'🐂'})
call matchadd('Conceal', ':dragon_face:', 10, -1, {'conceal':'🐲'})
call matchadd('Conceal', ':blowfish:', 10, -1, {'conceal':'🐡'})
call matchadd('Conceal', ':crocodile:', 10, -1, {'conceal':'🐊'})
call matchadd('Conceal', ':dromedary_camel:', 10, -1, {'conceal':'🐪'})
call matchadd('Conceal', ':leopard:', 10, -1, {'conceal':'🐆'})
call matchadd('Conceal', ':cat2:', 10, -1, {'conceal':'🐈'})
call matchadd('Conceal', ':poodle:', 10, -1, {'conceal':'🐩'})
call matchadd('Conceal', ':paw_prints:', 10, -1, {'conceal':'🐾'})
call matchadd('Conceal', ':bouquet:', 10, -1, {'conceal':'💐'})
call matchadd('Conceal', ':cherry_blossom:', 10, -1, {'conceal':'🌸'})
call matchadd('Conceal', ':tulip:', 10, -1, {'conceal':'🌷'})
call matchadd('Conceal', ':four_leaf_clover:', 10, -1, {'conceal':'🍀'})
call matchadd('Conceal', ':rose:', 10, -1, {'conceal':'🌹'})
call matchadd('Conceal', ':sunflower:', 10, -1, {'conceal':'🌻'})
call matchadd('Conceal', ':hibiscus:', 10, -1, {'conceal':'🌺'})
call matchadd('Conceal', ':maple_leaf:', 10, -1, {'conceal':'🍁'})
call matchadd('Conceal', ':leaves:', 10, -1, {'conceal':'🍃'})
call matchadd('Conceal', ':fallen_leaf:', 10, -1, {'conceal':'🍂'})
call matchadd('Conceal', ':herb:', 10, -1, {'conceal':'🌿'})
call matchadd('Conceal', ':mushroom:', 10, -1, {'conceal':'🍄'})
call matchadd('Conceal', ':cactus:', 10, -1, {'conceal':'🌵'})
call matchadd('Conceal', ':palm_tree:', 10, -1, {'conceal':'🌴'})
call matchadd('Conceal', ':evergreen_tree:', 10, -1, {'conceal':'🌲'})
call matchadd('Conceal', ':deciduous_tree:', 10, -1, {'conceal':'🌳'})
call matchadd('Conceal', ':chestnut:', 10, -1, {'conceal':'🌰'})
call matchadd('Conceal', ':seedling:', 10, -1, {'conceal':'🌱'})
call matchadd('Conceal', ':blossom:', 10, -1, {'conceal':'🌼'})
call matchadd('Conceal', ':ear_of_rice:', 10, -1, {'conceal':'🌾'})
call matchadd('Conceal', ':shell:', 10, -1, {'conceal':'🐚'})
call matchadd('Conceal', ':globe_with_meridians:', 10, -1, {'conceal':'🌐'})
call matchadd('Conceal', ':sun_with_face:', 10, -1, {'conceal':'🌞'})
call matchadd('Conceal', ':full_moon_with_face:', 10, -1, {'conceal':'🌝'})
call matchadd('Conceal', ':new_moon_with_face:', 10, -1, {'conceal':'🌚'})
call matchadd('Conceal', ':new_moon:', 10, -1, {'conceal':'🌑'})
call matchadd('Conceal', ':waxing_crescent_moon:', 10, -1, {'conceal':'🌒'})
call matchadd('Conceal', ':first_quarter_moon:', 10, -1, {'conceal':'🌓'})
call matchadd('Conceal', ':waxing_gibbous_moon:', 10, -1, {'conceal':'🌔'})
call matchadd('Conceal', ':full_moon:', 10, -1, {'conceal':'🌕'})
call matchadd('Conceal', ':waning_gibbous_moon:', 10, -1, {'conceal':'🌖'})
call matchadd('Conceal', ':last_quarter_moon:', 10, -1, {'conceal':'🌗'})
call matchadd('Conceal', ':waning_crescent_moon:', 10, -1, {'conceal':'🌘'})
call matchadd('Conceal', ':last_quarter_moon_with_face:', 10, -1, {'conceal':'🌜'})
call matchadd('Conceal', ':first_quarter_moon_with_face:', 10, -1, {'conceal':'🌛'})
call matchadd('Conceal', ':moon:', 10, -1, {'conceal':'🌔'})
call matchadd('Conceal', ':earth_africa:', 10, -1, {'conceal':'🌍'})
call matchadd('Conceal', ':earth_americas:', 10, -1, {'conceal':'🌎'})
call matchadd('Conceal', ':earth_asia:', 10, -1, {'conceal':'🌏'})
call matchadd('Conceal', ':volcano:', 10, -1, {'conceal':'🌋'})
call matchadd('Conceal', ':milky_way:', 10, -1, {'conceal':'🌌'})
call matchadd('Conceal', ':partly_sunny:', 10, -1, {'conceal':'⛅'})
call matchadd('Conceal', ':bamboo:', 10, -1, {'conceal':'🎍'})
call matchadd('Conceal', ':gift_heart:', 10, -1, {'conceal':'💝'})
call matchadd('Conceal', ':dolls:', 10, -1, {'conceal':'🎎'})
call matchadd('Conceal', ':school_satchel:', 10, -1, {'conceal':'🎒'})
call matchadd('Conceal', ':mortar_board:', 10, -1, {'conceal':'🎓'})
call matchadd('Conceal', ':flags:', 10, -1, {'conceal':'🎏'})
call matchadd('Conceal', ':fireworks:', 10, -1, {'conceal':'🎆'})
call matchadd('Conceal', ':sparkler:', 10, -1, {'conceal':'🎇'})
call matchadd('Conceal', ':wind_chime:', 10, -1, {'conceal':'🎐'})
call matchadd('Conceal', ':rice_scene:', 10, -1, {'conceal':'🎑'})
call matchadd('Conceal', ':jack_o_lantern:', 10, -1, {'conceal':'🎃'})
call matchadd('Conceal', ':ghost:', 10, -1, {'conceal':'👻'})
call matchadd('Conceal', ':santa:', 10, -1, {'conceal':'🎅'})
call matchadd('Conceal', ':christmas_tree:', 10, -1, {'conceal':'🎄'})
call matchadd('Conceal', ':gift:', 10, -1, {'conceal':'🎁'})
call matchadd('Conceal', ':bell:', 10, -1, {'conceal':'🔔'})
call matchadd('Conceal', ':no_bell:', 10, -1, {'conceal':'🔕'})
call matchadd('Conceal', ':tanabata_tree:', 10, -1, {'conceal':'🎋'})
call matchadd('Conceal', ':tada:', 10, -1, {'conceal':'🎉'})
call matchadd('Conceal', ':confetti_ball:', 10, -1, {'conceal':'🎊'})
call matchadd('Conceal', ':balloon:', 10, -1, {'conceal':'🎈'})
call matchadd('Conceal', ':crystal_ball:', 10, -1, {'conceal':'🔮'})
call matchadd('Conceal', ':cd:', 10, -1, {'conceal':'💿'})
call matchadd('Conceal', ':dvd:', 10, -1, {'conceal':'📀'})
call matchadd('Conceal', ':floppy_disk:', 10, -1, {'conceal':'💾'})
call matchadd('Conceal', ':camera:', 10, -1, {'conceal':'📷'})
call matchadd('Conceal', ':video_camera:', 10, -1, {'conceal':'📹'})
call matchadd('Conceal', ':movie_camera:', 10, -1, {'conceal':'🎥'})
call matchadd('Conceal', ':computer:', 10, -1, {'conceal':'💻'})
call matchadd('Conceal', ':tv:', 10, -1, {'conceal':'📺'})
call matchadd('Conceal', ':iphone:', 10, -1, {'conceal':'📱'})
" call matchadd('Conceal', ':phone:', 10, -1, {'conceal':'☎️'})
" call matchadd('Conceal', ':telephone:', 10, -1, {'conceal':'☎️'})
call matchadd('Conceal', ':telephone_receiver:', 10, -1, {'conceal':'📞'})
call matchadd('Conceal', ':pager:', 10, -1, {'conceal':'📟'})
call matchadd('Conceal', ':fax:', 10, -1, {'conceal':'📠'})
call matchadd('Conceal', ':minidisc:', 10, -1, {'conceal':'💽'})
call matchadd('Conceal', ':vhs:', 10, -1, {'conceal':'📼'})
call matchadd('Conceal', ':sound:', 10, -1, {'conceal':'🔉'})
call matchadd('Conceal', ':speaker:', 10, -1, {'conceal':'🔈'})
call matchadd('Conceal', ':mute:', 10, -1, {'conceal':'🔇'})
call matchadd('Conceal', ':loudspeaker:', 10, -1, {'conceal':'📢'})
call matchadd('Conceal', ':mega:', 10, -1, {'conceal':'📣'})
call matchadd('Conceal', ':hourglass:', 10, -1, {'conceal':'⌛'})
call matchadd('Conceal', ':hourglass_flowing_sand:', 10, -1, {'conceal':'⏳'})
call matchadd('Conceal', ':alarm_clock:', 10, -1, {'conceal':'⏰'})
call matchadd('Conceal', ':watch:', 10, -1, {'conceal':'⌚'})
call matchadd('Conceal', ':radio:', 10, -1, {'conceal':'📻'})
call matchadd('Conceal', ':satellite:', 10, -1, {'conceal':'📡'})
call matchadd('Conceal', ':loop:', 10, -1, {'conceal':'➿'})
call matchadd('Conceal', ':mag:', 10, -1, {'conceal':'🔍'})
call matchadd('Conceal', ':mag_right:', 10, -1, {'conceal':'🔎'})
" call matchadd('Conceal', ':unlock:', 10, -1, {'conceal':'🔓'})
" call matchadd('Conceal', ':lock:', 10, -1, {'conceal':'🔒'})
call matchadd('Conceal', ':lock_with_ink_pen:', 10, -1, {'conceal':'🔏'})
call matchadd('Conceal', ':closed_lock_with_key:', 10, -1, {'conceal':'🔐'})
call matchadd('Conceal', ':key:', 10, -1, {'conceal':'🔑'})
call matchadd('Conceal', ':bulb:', 10, -1, {'conceal':'💡'})
call matchadd('Conceal', ':flashlight:', 10, -1, {'conceal':'🔦'})
call matchadd('Conceal', ':high_brightness:', 10, -1, {'conceal':'🔆'})
call matchadd('Conceal', ':low_brightness:', 10, -1, {'conceal':'🔅'})
call matchadd('Conceal', ':electric_plug:', 10, -1, {'conceal':'🔌'})
call matchadd('Conceal', ':battery:', 10, -1, {'conceal':'🔋'})
call matchadd('Conceal', ':calling:', 10, -1, {'conceal':'📲'})
call matchadd('Conceal', ':email:', 10, -1, {'conceal':'📧'})
call matchadd('Conceal', ':mailbox:', 10, -1, {'conceal':'📫'})
call matchadd('Conceal', ':postbox:', 10, -1, {'conceal':'📮'})
call matchadd('Conceal', ':bath:', 10, -1, {'conceal':'🛀'})
call matchadd('Conceal', ':bathtub:', 10, -1, {'conceal':'🛁'})
call matchadd('Conceal', ':shower:', 10, -1, {'conceal':'🚿'})
call matchadd('Conceal', ':toilet:', 10, -1, {'conceal':'🚽'})
call matchadd('Conceal', ':wrench:', 10, -1, {'conceal':'🔧'})
call matchadd('Conceal', ':nut_and_bolt:', 10, -1, {'conceal':'🔩'})
call matchadd('Conceal', ':hammer:', 10, -1, {'conceal':'🔨'})
call matchadd('Conceal', ':seat:', 10, -1, {'conceal':'💺'})
call matchadd('Conceal', ':moneybag:', 10, -1, {'conceal':'💰'})
call matchadd('Conceal', ':yen:', 10, -1, {'conceal':'💴'})
call matchadd('Conceal', ':dollar:', 10, -1, {'conceal':'💵'})
call matchadd('Conceal', ':pound:', 10, -1, {'conceal':'💷'})
call matchadd('Conceal', ':euro:', 10, -1, {'conceal':'💶'})
call matchadd('Conceal', ':credit_card:', 10, -1, {'conceal':'💳'})
call matchadd('Conceal', ':money_with_wings:', 10, -1, {'conceal':'💸'})
call matchadd('Conceal', ':e-mail:', 10, -1, {'conceal':'📧'})
call matchadd('Conceal', ':inbox_tray:', 10, -1, {'conceal':'📥'})
call matchadd('Conceal', ':outbox_tray:', 10, -1, {'conceal':'📤'})
call matchadd('Conceal', ':envelope:', 10, -1, {'conceal':'✉️'})
call matchadd('Conceal', ':incoming_envelope:', 10, -1, {'conceal':'📨'})
call matchadd('Conceal', ':postal_horn:', 10, -1, {'conceal':'📯'})
call matchadd('Conceal', ':mailbox_closed:', 10, -1, {'conceal':'📪'})
call matchadd('Conceal', ':mailbox_with_mail:', 10, -1, {'conceal':'📬'})
call matchadd('Conceal', ':mailbox_with_no_mail:', 10, -1, {'conceal':'📭'})
call matchadd('Conceal', ':door:', 10, -1, {'conceal':'🚪'})
call matchadd('Conceal', ':smoking:', 10, -1, {'conceal':'🚬'})
call matchadd('Conceal', ':bomb:', 10, -1, {'conceal':'💣'})
call matchadd('Conceal', ':gun:', 10, -1, {'conceal':'🔫'})
call matchadd('Conceal', ':hocho:', 10, -1, {'conceal':'🔪'})
call matchadd('Conceal', ':pill:', 10, -1, {'conceal':'💊'})
call matchadd('Conceal', ':syringe:', 10, -1, {'conceal':'💉'})
call matchadd('Conceal', ':page_facing_up:', 10, -1, {'conceal':'📄'})
call matchadd('Conceal', ':page_with_curl:', 10, -1, {'conceal':'📃'})
call matchadd('Conceal', ':bookmark_tabs:', 10, -1, {'conceal':'📑'})
call matchadd('Conceal', ':bar_chart:', 10, -1, {'conceal':'📊'})
call matchadd('Conceal', ':chart_with_upwards_trend:', 10, -1, {'conceal':'📈'})
call matchadd('Conceal', ':chart_with_downwards_trend:', 10, -1, {'conceal':'📉'})
call matchadd('Conceal', ':scroll:', 10, -1, {'conceal':'📜'})
call matchadd('Conceal', ':clipboard:', 10, -1, {'conceal':'📋'})
call matchadd('Conceal', ':calendar:', 10, -1, {'conceal':'📆'})
call matchadd('Conceal', ':date:', 10, -1, {'conceal':'📅'})
call matchadd('Conceal', ':card_index:', 10, -1, {'conceal':'📇'})
call matchadd('Conceal', ':file_folder:', 10, -1, {'conceal':'📁'})
call matchadd('Conceal', ':open_file_folder:', 10, -1, {'conceal':'📂'})
call matchadd('Conceal', ':scissors:', 10, -1, {'conceal':'✂️'})
call matchadd('Conceal', ':pushpin:', 10, -1, {'conceal':'📌'})
call matchadd('Conceal', ':paperclip:', 10, -1, {'conceal':'📎'})
" call matchadd('Conceal', ':black_nib:', 10, -1, {'conceal':'✒️'})
" call matchadd('Conceal', ':pencil2:', 10, -1, {'conceal':'✏️'})
call matchadd('Conceal', ':straight_ruler:', 10, -1, {'conceal':'📏'})
call matchadd('Conceal', ':triangular_ruler:', 10, -1, {'conceal':'📐'})
call matchadd('Conceal', ':closed_book:', 10, -1, {'conceal':'📕'})
call matchadd('Conceal', ':green_book:', 10, -1, {'conceal':'📗'})
call matchadd('Conceal', ':blue_book:', 10, -1, {'conceal':'📘'})
call matchadd('Conceal', ':orange_book:', 10, -1, {'conceal':'📙'})
call matchadd('Conceal', ':notebook:', 10, -1, {'conceal':'📓'})
call matchadd('Conceal', ':notebook_with_decorative_cover:', 10, -1, {'conceal':'📔'})
call matchadd('Conceal', ':ledger:', 10, -1, {'conceal':'📒'})
call matchadd('Conceal', ':books:', 10, -1, {'conceal':'📚'})
call matchadd('Conceal', ':bookmark:', 10, -1, {'conceal':'🔖'})
call matchadd('Conceal', ':name_badge:', 10, -1, {'conceal':'📛'})
call matchadd('Conceal', ':microscope:', 10, -1, {'conceal':'🔬'})
call matchadd('Conceal', ':telescope:', 10, -1, {'conceal':'🔭'})
call matchadd('Conceal', ':newspaper:', 10, -1, {'conceal':'📰'})
call matchadd('Conceal', ':football:', 10, -1, {'conceal':'🏈'})
call matchadd('Conceal', ':basketball:', 10, -1, {'conceal':'🏀'})
call matchadd('Conceal', ':soccer:', 10, -1, {'conceal':'⚽'})
call matchadd('Conceal', ':baseball:', 10, -1, {'conceal':'⚾'})
call matchadd('Conceal', ':tennis:', 10, -1, {'conceal':'🎾'})
call matchadd('Conceal', ':8ball:', 10, -1, {'conceal':'🎱'})
call matchadd('Conceal', ':rugby_football:', 10, -1, {'conceal':'🏉'})
call matchadd('Conceal', ':bowling:', 10, -1, {'conceal':'🎳'})
call matchadd('Conceal', ':golf:', 10, -1, {'conceal':'⛳'})
call matchadd('Conceal', ':mountain_bicyclist:', 10, -1, {'conceal':'🚵'})
call matchadd('Conceal', ':bicyclist:', 10, -1, {'conceal':'🚴'})
call matchadd('Conceal', ':horse_racing:', 10, -1, {'conceal':'🏇'})
call matchadd('Conceal', ':snowboarder:', 10, -1, {'conceal':'🏂'})
call matchadd('Conceal', ':swimmer:', 10, -1, {'conceal':'🏊'})
call matchadd('Conceal', ':surfer:', 10, -1, {'conceal':'🏄'})
call matchadd('Conceal', ':ski:', 10, -1, {'conceal':'🎿'})
" call matchadd('Conceal', ':spades:', 10, -1, {'conceal':'♠️'})
" call matchadd('Conceal', ':hearts:', 10, -1, {'conceal':'♥️'})
" call matchadd('Conceal', ':clubs:', 10, -1, {'conceal':'♣️'})
" call matchadd('Conceal', ':diamonds:', 10, -1, {'conceal':'♦️'})
call matchadd('Conceal', ':gem:', 10, -1, {'conceal':'💎'})
call matchadd('Conceal', ':ring:', 10, -1, {'conceal':'💍'})
call matchadd('Conceal', ':trophy:', 10, -1, {'conceal':'🏆'})
call matchadd('Conceal', ':musical_score:', 10, -1, {'conceal':'🎼'})
call matchadd('Conceal', ':musical_keyboard:', 10, -1, {'conceal':'🎹'})
call matchadd('Conceal', ':violin:', 10, -1, {'conceal':'🎻'})
call matchadd('Conceal', ':space_invader:', 10, -1, {'conceal':'👾'})
call matchadd('Conceal', ':video_game:', 10, -1, {'conceal':'🎮'})
call matchadd('Conceal', ':black_joker:', 10, -1, {'conceal':'🃏'})
call matchadd('Conceal', ':flower_playing_cards:', 10, -1, {'conceal':'🎴'})
call matchadd('Conceal', ':game_die:', 10, -1, {'conceal':'🎲'})
call matchadd('Conceal', ':dart:', 10, -1, {'conceal':'🎯'})
call matchadd('Conceal', ':mahjong:', 10, -1, {'conceal':'🀄'})
call matchadd('Conceal', ':clapper:', 10, -1, {'conceal':'🎬'})
call matchadd('Conceal', ':memo:', 10, -1, {'conceal':'📝'})
call matchadd('Conceal', ':pencil:', 10, -1, {'conceal':'📝'})
call matchadd('Conceal', ':book:', 10, -1, {'conceal':'📖'})
call matchadd('Conceal', ':art:', 10, -1, {'conceal':'🎨'})
call matchadd('Conceal', ':microphone:', 10, -1, {'conceal':'🎤'})
call matchadd('Conceal', ':headphones:', 10, -1, {'conceal':'🎧'})
call matchadd('Conceal', ':trumpet:', 10, -1, {'conceal':'🎺'})
call matchadd('Conceal', ':saxophone:', 10, -1, {'conceal':'🎷'})
call matchadd('Conceal', ':guitar:', 10, -1, {'conceal':'🎸'})
call matchadd('Conceal', ':shoe:', 10, -1, {'conceal':'👞'})
call matchadd('Conceal', ':sandal:', 10, -1, {'conceal':'👡'})
call matchadd('Conceal', ':high_heel:', 10, -1, {'conceal':'👠'})
call matchadd('Conceal', ':lipstick:', 10, -1, {'conceal':'💄'})
call matchadd('Conceal', ':boot:', 10, -1, {'conceal':'👢'})
call matchadd('Conceal', ':shirt:', 10, -1, {'conceal':'👕'})
call matchadd('Conceal', ':tshirt:', 10, -1, {'conceal':'👕'})
call matchadd('Conceal', ':necktie:', 10, -1, {'conceal':'👔'})
call matchadd('Conceal', ':womans_clothes:', 10, -1, {'conceal':'👚'})
call matchadd('Conceal', ':dress:', 10, -1, {'conceal':'👗'})
call matchadd('Conceal', ':running_shirt_with_sash:', 10, -1, {'conceal':'🎽'})
call matchadd('Conceal', ':jeans:', 10, -1, {'conceal':'👖'})
call matchadd('Conceal', ':kimono:', 10, -1, {'conceal':'👘'})
call matchadd('Conceal', ':bikini:', 10, -1, {'conceal':'👙'})
call matchadd('Conceal', ':ribbon:', 10, -1, {'conceal':'🎀'})
call matchadd('Conceal', ':tophat:', 10, -1, {'conceal':'🎩'})
call matchadd('Conceal', ':crown:', 10, -1, {'conceal':'👑'})
call matchadd('Conceal', ':womans_hat:', 10, -1, {'conceal':'👒'})
call matchadd('Conceal', ':mans_shoe:', 10, -1, {'conceal':'👞'})
call matchadd('Conceal', ':closed_umbrella:', 10, -1, {'conceal':'🌂'})
call matchadd('Conceal', ':briefcase:', 10, -1, {'conceal':'💼'})
call matchadd('Conceal', ':handbag:', 10, -1, {'conceal':'👜'})
call matchadd('Conceal', ':pouch:', 10, -1, {'conceal':'👝'})
call matchadd('Conceal', ':purse:', 10, -1, {'conceal':'👛'})
call matchadd('Conceal', ':eyeglasses:', 10, -1, {'conceal':'👓'})
call matchadd('Conceal', ':fishing_pole_and_fish:', 10, -1, {'conceal':'🎣'})
call matchadd('Conceal', ':coffee:', 10, -1, {'conceal':'☕'})
call matchadd('Conceal', ':tea:', 10, -1, {'conceal':'🍵'})
call matchadd('Conceal', ':sake:', 10, -1, {'conceal':'🍶'})
call matchadd('Conceal', ':baby_bottle:', 10, -1, {'conceal':'🍼'})
call matchadd('Conceal', ':beer:', 10, -1, {'conceal':'🍺'})
call matchadd('Conceal', ':beers:', 10, -1, {'conceal':'🍻'})
call matchadd('Conceal', ':cocktail:', 10, -1, {'conceal':'🍸'})
call matchadd('Conceal', ':tropical_drink:', 10, -1, {'conceal':'🍹'})
call matchadd('Conceal', ':wine_glass:', 10, -1, {'conceal':'🍷'})
call matchadd('Conceal', ':fork_and_knife:', 10, -1, {'conceal':'🍴'})
call matchadd('Conceal', ':pizza:', 10, -1, {'conceal':'🍕'})
call matchadd('Conceal', ':hamburger:', 10, -1, {'conceal':'🍔'})
call matchadd('Conceal', ':fries:', 10, -1, {'conceal':'🍟'})
call matchadd('Conceal', ':poultry_leg:', 10, -1, {'conceal':'🍗'})
call matchadd('Conceal', ':meat_on_bone:', 10, -1, {'conceal':'🍖'})
call matchadd('Conceal', ':spaghetti:', 10, -1, {'conceal':'🍝'})
call matchadd('Conceal', ':curry:', 10, -1, {'conceal':'🍛'})
call matchadd('Conceal', ':fried_shrimp:', 10, -1, {'conceal':'🍤'})
call matchadd('Conceal', ':bento:', 10, -1, {'conceal':'🍱'})
call matchadd('Conceal', ':sushi:', 10, -1, {'conceal':'🍣'})
call matchadd('Conceal', ':fish_cake:', 10, -1, {'conceal':'🍥'})
call matchadd('Conceal', ':rice_ball:', 10, -1, {'conceal':'🍙'})
call matchadd('Conceal', ':rice_cracker:', 10, -1, {'conceal':'🍘'})
call matchadd('Conceal', ':rice:', 10, -1, {'conceal':'🍚'})
call matchadd('Conceal', ':ramen:', 10, -1, {'conceal':'🍜'})
call matchadd('Conceal', ':stew:', 10, -1, {'conceal':'🍲'})
call matchadd('Conceal', ':oden:', 10, -1, {'conceal':'🍢'})
call matchadd('Conceal', ':dango:', 10, -1, {'conceal':'🍡'})
call matchadd('Conceal', ':egg:', 10, -1, {'conceal':'🥚'})
call matchadd('Conceal', ':bread:', 10, -1, {'conceal':'🍞'})
call matchadd('Conceal', ':doughnut:', 10, -1, {'conceal':'🍩'})
call matchadd('Conceal', ':custard:', 10, -1, {'conceal':'🍮'})
call matchadd('Conceal', ':icecream:', 10, -1, {'conceal':'🍦'})
call matchadd('Conceal', ':ice_cream:', 10, -1, {'conceal':'🍨'})
call matchadd('Conceal', ':shaved_ice:', 10, -1, {'conceal':'🍧'})
call matchadd('Conceal', ':birthday:', 10, -1, {'conceal':'🎂'})
call matchadd('Conceal', ':cake:', 10, -1, {'conceal':'🍰'})
call matchadd('Conceal', ':cookie:', 10, -1, {'conceal':'🍪'})
call matchadd('Conceal', ':chocolate_bar:', 10, -1, {'conceal':'🍫'})
call matchadd('Conceal', ':candy:', 10, -1, {'conceal':'🍬'})
call matchadd('Conceal', ':lollipop:', 10, -1, {'conceal':'🍭'})
call matchadd('Conceal', ':honey_pot:', 10, -1, {'conceal':'🍯'})
call matchadd('Conceal', ':apple:', 10, -1, {'conceal':'🍎'})
call matchadd('Conceal', ':green_apple:', 10, -1, {'conceal':'🍏'})
call matchadd('Conceal', ':tangerine:', 10, -1, {'conceal':'🍊'})
call matchadd('Conceal', ':lemon:', 10, -1, {'conceal':'🍋'})
call matchadd('Conceal', ':cherries:', 10, -1, {'conceal':'🍒'})
call matchadd('Conceal', ':grapes:', 10, -1, {'conceal':'🍇'})
call matchadd('Conceal', ':watermelon:', 10, -1, {'conceal':'🍉'})
call matchadd('Conceal', ':strawberry:', 10, -1, {'conceal':'🍓'})
call matchadd('Conceal', ':peach:', 10, -1, {'conceal':'🍑'})
call matchadd('Conceal', ':melon:', 10, -1, {'conceal':'🍈'})
call matchadd('Conceal', ':banana:', 10, -1, {'conceal':'🍌'})
call matchadd('Conceal', ':pear:', 10, -1, {'conceal':'🍐'})
call matchadd('Conceal', ':pineapple:', 10, -1, {'conceal':'🍍'})
call matchadd('Conceal', ':sweet_potato:', 10, -1, {'conceal':'🍠'})
call matchadd('Conceal', ':eggplant:', 10, -1, {'conceal':'🍆'})
call matchadd('Conceal', ':tomato:', 10, -1, {'conceal':'🍅'})
call matchadd('Conceal', ':corn:', 10, -1, {'conceal':'🌽'})
call matchadd('Conceal', ':house:', 10, -1, {'conceal':'🏠'})
call matchadd('Conceal', ':house_with_garden:', 10, -1, {'conceal':'🏡'})
call matchadd('Conceal', ':school:', 10, -1, {'conceal':'🏫'})
call matchadd('Conceal', ':office:', 10, -1, {'conceal':'🏢'})
call matchadd('Conceal', ':post_office:', 10, -1, {'conceal':'🏣'})
call matchadd('Conceal', ':hospital:', 10, -1, {'conceal':'🏥'})
call matchadd('Conceal', ':bank:', 10, -1, {'conceal':'🏦'})
call matchadd('Conceal', ':convenience_store:', 10, -1, {'conceal':'🏪'})
call matchadd('Conceal', ':love_hotel:', 10, -1, {'conceal':'🏩'})
call matchadd('Conceal', ':hotel:', 10, -1, {'conceal':'🏨'})
call matchadd('Conceal', ':wedding:', 10, -1, {'conceal':'💒'})
call matchadd('Conceal', ':church:', 10, -1, {'conceal':'⛪'})
call matchadd('Conceal', ':department_store:', 10, -1, {'conceal':'🏬'})
call matchadd('Conceal', ':european_post_office:', 10, -1, {'conceal':'🏤'})
call matchadd('Conceal', ':city_sunrise:', 10, -1, {'conceal':'🌇'})
call matchadd('Conceal', ':city_sunset:', 10, -1, {'conceal':'🌆'})
call matchadd('Conceal', ':japanese_castle:', 10, -1, {'conceal':'🏯'})
call matchadd('Conceal', ':european_castle:', 10, -1, {'conceal':'🏰'})
call matchadd('Conceal', ':tent:', 10, -1, {'conceal':'⛺'})
call matchadd('Conceal', ':factory:', 10, -1, {'conceal':'🏭'})
call matchadd('Conceal', ':tokyo_tower:', 10, -1, {'conceal':'🗼'})
call matchadd('Conceal', ':japan:', 10, -1, {'conceal':'🗾'})
call matchadd('Conceal', ':mount_fuji:', 10, -1, {'conceal':'🗻'})
call matchadd('Conceal', ':sunrise_over_mountains:', 10, -1, {'conceal':'🌄'})
call matchadd('Conceal', ':sunrise:', 10, -1, {'conceal':'🌅'})
call matchadd('Conceal', ':stars:', 10, -1, {'conceal':'🌠'})
call matchadd('Conceal', ':statue_of_liberty:', 10, -1, {'conceal':'🗽'})
call matchadd('Conceal', ':bridge_at_night:', 10, -1, {'conceal':'🌉'})
call matchadd('Conceal', ':carousel_horse:', 10, -1, {'conceal':'🎠'})
call matchadd('Conceal', ':rainbow:', 10, -1, {'conceal':'🌈'})
call matchadd('Conceal', ':ferris_wheel:', 10, -1, {'conceal':'🎡'})
call matchadd('Conceal', ':fountain:', 10, -1, {'conceal':'⛲'})
call matchadd('Conceal', ':roller_coaster:', 10, -1, {'conceal':'🎢'})
call matchadd('Conceal', ':ship:', 10, -1, {'conceal':'🚢'})
call matchadd('Conceal', ':speedboat:', 10, -1, {'conceal':'🚤'})
call matchadd('Conceal', ':boat:', 10, -1, {'conceal':'⛵'})
call matchadd('Conceal', ':sailboat:', 10, -1, {'conceal':'⛵'})
call matchadd('Conceal', ':rowboat:', 10, -1, {'conceal':'🚣'})
call matchadd('Conceal', ':anchor:', 10, -1, {'conceal':'⚓'})
call matchadd('Conceal', ':rocket:', 10, -1, {'conceal':'🚀'})
call matchadd('Conceal', ':airplane:', 10, -1, {'conceal':'✈️'})
call matchadd('Conceal', ':helicopter:', 10, -1, {'conceal':'🚁'})
call matchadd('Conceal', ':steam_locomotive:', 10, -1, {'conceal':'🚂'})
call matchadd('Conceal', ':tram:', 10, -1, {'conceal':'🚊'})
call matchadd('Conceal', ':mountain_railway:', 10, -1, {'conceal':'🚞'})
call matchadd('Conceal', ':bike:', 10, -1, {'conceal':'🚲'})
call matchadd('Conceal', ':aerial_tramway:', 10, -1, {'conceal':'🚡'})
call matchadd('Conceal', ':suspension_railway:', 10, -1, {'conceal':'🚟'})
call matchadd('Conceal', ':mountain_cableway:', 10, -1, {'conceal':'🚠'})
call matchadd('Conceal', ':tractor:', 10, -1, {'conceal':'🚜'})
call matchadd('Conceal', ':blue_car:', 10, -1, {'conceal':'🚙'})
call matchadd('Conceal', ':oncoming_automobile:', 10, -1, {'conceal':'🚘'})
call matchadd('Conceal', ':car:', 10, -1, {'conceal':'🚗'})
call matchadd('Conceal', ':red_car:', 10, -1, {'conceal':'🚗'})
call matchadd('Conceal', ':taxi:', 10, -1, {'conceal':'🚕'})
call matchadd('Conceal', ':oncoming_taxi:', 10, -1, {'conceal':'🚖'})
call matchadd('Conceal', ':articulated_lorry:', 10, -1, {'conceal':'🚛'})
call matchadd('Conceal', ':bus:', 10, -1, {'conceal':'🚌'})
call matchadd('Conceal', ':oncoming_bus:', 10, -1, {'conceal':'🚍'})
call matchadd('Conceal', ':rotating_light:', 10, -1, {'conceal':'🚨'})
call matchadd('Conceal', ':police_car:', 10, -1, {'conceal':'🚓'})
call matchadd('Conceal', ':oncoming_police_car:', 10, -1, {'conceal':'🚔'})
call matchadd('Conceal', ':fire_engine:', 10, -1, {'conceal':'🚒'})
call matchadd('Conceal', ':ambulance:', 10, -1, {'conceal':'🚑'})
call matchadd('Conceal', ':minibus:', 10, -1, {'conceal':'🚐'})
call matchadd('Conceal', ':truck:', 10, -1, {'conceal':'🚚'})
call matchadd('Conceal', ':train:', 10, -1, {'conceal':'🚋'})
call matchadd('Conceal', ':station:', 10, -1, {'conceal':'🚉'})
call matchadd('Conceal', ':train2:', 10, -1, {'conceal':'🚆'})
call matchadd('Conceal', ':bullettrain_front:', 10, -1, {'conceal':'🚅'})
call matchadd('Conceal', ':bullettrain_side:', 10, -1, {'conceal':'🚄'})
call matchadd('Conceal', ':light_rail:', 10, -1, {'conceal':'🚈'})
call matchadd('Conceal', ':monorail:', 10, -1, {'conceal':'🚝'})
call matchadd('Conceal', ':railway_car:', 10, -1, {'conceal':'🚃'})
call matchadd('Conceal', ':trolleybus:', 10, -1, {'conceal':'🚎'})
call matchadd('Conceal', ':ticket:', 10, -1, {'conceal':'🎫'})
call matchadd('Conceal', ':fuelpump:', 10, -1, {'conceal':'⛽'})
call matchadd('Conceal', ':vertical_traffic_light:', 10, -1, {'conceal':'🚦'})
call matchadd('Conceal', ':traffic_light:', 10, -1, {'conceal':'🚥'})
call matchadd('Conceal', ':warning:', 10, -1, {'conceal':'⚠️'})
call matchadd('Conceal', ':construction:', 10, -1, {'conceal':'🚧'})
call matchadd('Conceal', ':beginner:', 10, -1, {'conceal':'🔰'})
call matchadd('Conceal', ':atm:', 10, -1, {'conceal':'🏧'})
call matchadd('Conceal', ':slot_machine:', 10, -1, {'conceal':'🎰'})
call matchadd('Conceal', ':busstop:', 10, -1, {'conceal':'🚏'})
call matchadd('Conceal', ':barber:', 10, -1, {'conceal':'💈'})
call matchadd('Conceal', ':hotsprings:', 10, -1, {'conceal':'♨️'})
call matchadd('Conceal', ':checkered_flag:', 10, -1, {'conceal':'🏁'})
call matchadd('Conceal', ':crossed_flags:', 10, -1, {'conceal':'🎌'})
call matchadd('Conceal', ':izakaya_lantern:', 10, -1, {'conceal':'🏮'})
call matchadd('Conceal', ':moyai:', 10, -1, {'conceal':'🗿'})
call matchadd('Conceal', ':circus_tent:', 10, -1, {'conceal':'🎪'})
call matchadd('Conceal', ':performing_arts:', 10, -1, {'conceal':'🎭'})
call matchadd('Conceal', ':round_pushpin:', 10, -1, {'conceal':'📍'})
call matchadd('Conceal', ':triangular_flag_on_post:', 10, -1, {'conceal':'🚩'})
" call matchadd('Conceal', ':jp:', 10, -1, {'conceal':'🇯🇵'})
" call matchadd('Conceal', ':kr:', 10, -1, {'conceal':'🇰🇷'})
" call matchadd('Conceal', ':cn:', 10, -1, {'conceal':'🇨🇳'})
" call matchadd('Conceal', ':us:', 10, -1, {'conceal':'🇺🇸'})
" call matchadd('Conceal', ':fr:', 10, -1, {'conceal':'🇫🇷'})
" call matchadd('Conceal', ':es:', 10, -1, {'conceal':'🇪🇸'})
" call matchadd('Conceal', ':it:', 10, -1, {'conceal':'🇮🇹'})
" call matchadd('Conceal', ':ru:', 10, -1, {'conceal':'🇷🇺'})
" call matchadd('Conceal', ':gb:', 10, -1, {'conceal':'🇬🇧'})
" call matchadd('Conceal', ':uk:', 10, -1, {'conceal':'🇬🇧'})
" call matchadd('Conceal', ':de:', 10, -1, {'conceal':'🇩🇪'})
" call matchadd('Conceal', ':one:', 10, -1, {'conceal':'1️⃣'})
" call matchadd('Conceal', ':two:', 10, -1, {'conceal':'2️⃣'})
" call matchadd('Conceal', ':three:', 10, -1, {'conceal':'3️⃣'})
" call matchadd('Conceal', ':four:', 10, -1, {'conceal':'4️⃣'})
" call matchadd('Conceal', ':five:', 10, -1, {'conceal':'5️⃣'})
" call matchadd('Conceal', ':six:', 10, -1, {'conceal':'6️⃣'})
" call matchadd('Conceal', ':seven:', 10, -1, {'conceal':'7️⃣'})
" call matchadd('Conceal', ':eight:', 10, -1, {'conceal':'8️⃣'})
" call matchadd('Conceal', ':nine:', 10, -1, {'conceal':'9️⃣'})
call matchadd('Conceal', ':keycap_ten:', 10, -1, {'conceal':'🔟'})
call matchadd('Conceal', ':1234:', 10, -1, {'conceal':'🔢'})
" call matchadd('Conceal', ':zero:', 10, -1, {'conceal':'0️⃣'})
" call matchadd('Conceal', ':hash:', 10, -1, {'conceal':'#️⃣'})
call matchadd('Conceal', ':symbols:', 10, -1, {'conceal':'🔣'})
" call matchadd('Conceal', ':arrow_backward:', 10, -1, {'conceal':'◀️'})
" call matchadd('Conceal', ':arrow_down:', 10, -1, {'conceal':'⬇️'})
" call matchadd('Conceal', ':arrow_forward:', 10, -1, {'conceal':'▶️'})
" call matchadd('Conceal', ':arrow_left:', 10, -1, {'conceal':'⬅️'})
call matchadd('Conceal', ':capital_abcd:', 10, -1, {'conceal':'🔠'})
call matchadd('Conceal', ':abcd:', 10, -1, {'conceal':'🔡'})
call matchadd('Conceal', ':abc:', 10, -1, {'conceal':'🔤'})
" call matchadd('Conceal', ':arrow_lower_left:', 10, -1, {'conceal':'↙️'})
" call matchadd('Conceal', ':arrow_lower_right:', 10, -1, {'conceal':'↘️'})
" call matchadd('Conceal', ':arrow_right:', 10, -1, {'conceal':'➡️'})
" call matchadd('Conceal', ':arrow_up:', 10, -1, {'conceal':'⬆️'})
" call matchadd('Conceal', ':arrow_upper_left:', 10, -1, {'conceal':'↖️'})
" call matchadd('Conceal', ':arrow_upper_right:', 10, -1, {'conceal':'↗️'})
call matchadd('Conceal', ':arrow_double_down:', 10, -1, {'conceal':'⏬'})
call matchadd('Conceal', ':arrow_double_up:', 10, -1, {'conceal':'⏫'})
call matchadd('Conceal', ':arrow_down_small:', 10, -1, {'conceal':'🔽'})
" call matchadd('Conceal', ':arrow_heading_down:', 10, -1, {'conceal':'⤵️'})
" call matchadd('Conceal', ':arrow_heading_up:', 10, -1, {'conceal':'⤴️'})
" call matchadd('Conceal', ':leftwards_arrow_with_hook:', 10, -1, {'conceal':'↩️'})
" call matchadd('Conceal', ':arrow_right_hook:', 10, -1, {'conceal':'↪️'})
" call matchadd('Conceal', ':left_right_arrow:', 10, -1, {'conceal':'↔️'})
" call matchadd('Conceal', ':arrow_up_down:', 10, -1, {'conceal':'↕️'})
call matchadd('Conceal', ':arrow_up_small:', 10, -1, {'conceal':'🔼'})
call matchadd('Conceal', ':arrows_clockwise:', 10, -1, {'conceal':'🔃'})
call matchadd('Conceal', ':arrows_counterclockwise:', 10, -1, {'conceal':'🔄'})
call matchadd('Conceal', ':rewind:', 10, -1, {'conceal':'⏪'})
call matchadd('Conceal', ':fast_forward:', 10, -1, {'conceal':'⏩'})
" call matchadd('Conceal', ':information_source:', 10, -1, {'conceal':'ℹ️'})
call matchadd('Conceal', ':ok:', 10, -1, {'conceal':'🆗'})
call matchadd('Conceal', ':twisted_rightwards_arrows:', 10, -1, {'conceal':'🔀'})
call matchadd('Conceal', ':repeat:', 10, -1, {'conceal':'🔁'})
call matchadd('Conceal', ':repeat_one:', 10, -1, {'conceal':'🔂'})
call matchadd('Conceal', ':new:', 10, -1, {'conceal':'🆕'})
call matchadd('Conceal', ':top:', 10, -1, {'conceal':'🔝'})
call matchadd('Conceal', ':up:', 10, -1, {'conceal':'🆙'})
call matchadd('Conceal', ':cool:', 10, -1, {'conceal':'🆒'})
call matchadd('Conceal', ':free:', 10, -1, {'conceal':'🆓'})
call matchadd('Conceal', ':ng:', 10, -1, {'conceal':'🆖'})
call matchadd('Conceal', ':cinema:', 10, -1, {'conceal':'🎦'})
call matchadd('Conceal', ':koko:', 10, -1, {'conceal':'🈁'})
call matchadd('Conceal', ':signal_strength:', 10, -1, {'conceal':'📶'})
call matchadd('Conceal', ':u5272:', 10, -1, {'conceal':'🈹'})
call matchadd('Conceal', ':u5408:', 10, -1, {'conceal':'🈴'})
call matchadd('Conceal', ':u55b6:', 10, -1, {'conceal':'🈺'})
call matchadd('Conceal', ':u6307:', 10, -1, {'conceal':'🈯'})
" call matchadd('Conceal', ':u6708:', 10, -1, {'conceal':'🈷️'})
call matchadd('Conceal', ':u6709:', 10, -1, {'conceal':'🈶'})
call matchadd('Conceal', ':u6e80:', 10, -1, {'conceal':'🈵'})
call matchadd('Conceal', ':u7121:', 10, -1, {'conceal':'🈚'})
call matchadd('Conceal', ':u7533:', 10, -1, {'conceal':'🈸'})
call matchadd('Conceal', ':u7a7a:', 10, -1, {'conceal':'🈳'})
call matchadd('Conceal', ':u7981:', 10, -1, {'conceal':'🈲'})
" call matchadd('Conceal', ':sa:', 10, -1, {'conceal':'🈂️'})
call matchadd('Conceal', ':restroom:', 10, -1, {'conceal':'🚻'})
call matchadd('Conceal', ':mens:', 10, -1, {'conceal':'🚹'})
call matchadd('Conceal', ':womens:', 10, -1, {'conceal':'🚺'})
call matchadd('Conceal', ':baby_symbol:', 10, -1, {'conceal':'🚼'})
call matchadd('Conceal', ':no_smoking:', 10, -1, {'conceal':'🚭'})
call matchadd('Conceal', ':parking:', 10, -1, {'conceal':'🅿️'})
call matchadd('Conceal', ':wheelchair:', 10, -1, {'conceal':'♿'})
call matchadd('Conceal', ':metro:', 10, -1, {'conceal':'🚇'})
call matchadd('Conceal', ':baggage_claim:', 10, -1, {'conceal':'🛄'})
call matchadd('Conceal', ':accept:', 10, -1, {'conceal':'🉑'})
call matchadd('Conceal', ':wc:', 10, -1, {'conceal':'🚾'})
call matchadd('Conceal', ':potable_water:', 10, -1, {'conceal':'🚰'})
call matchadd('Conceal', ':put_litter_in_its_place:', 10, -1, {'conceal':'🚮'})
" call matchadd('Conceal', ':secret:', 10, -1, {'conceal':'㊙️'})
" call matchadd('Conceal', ':congratulations:', 10, -1, {'conceal':'㊗️'})
" call matchadd('Conceal', ':m:', 10, -1, {'conceal':'Ⓜ️'})
call matchadd('Conceal', ':passport_control:', 10, -1, {'conceal':'🛂'})
call matchadd('Conceal', ':left_luggage:', 10, -1, {'conceal':'🛅'})
call matchadd('Conceal', ':customs:', 10, -1, {'conceal':'🛃'})
call matchadd('Conceal', ':ideograph_advantage:', 10, -1, {'conceal':'🉐'})
call matchadd('Conceal', ':cl:', 10, -1, {'conceal':'🆑'})
call matchadd('Conceal', ':sos:', 10, -1, {'conceal':'🆘'})
call matchadd('Conceal', ':id:', 10, -1, {'conceal':'🆔'})
call matchadd('Conceal', ':no_entry_sign:', 10, -1, {'conceal':'🚫'})
call matchadd('Conceal', ':underage:', 10, -1, {'conceal':'🔞'})
call matchadd('Conceal', ':no_mobile_phones:', 10, -1, {'conceal':'📵'})
call matchadd('Conceal', ':do_not_litter:', 10, -1, {'conceal':'🚯'})
call matchadd('Conceal', ':non-potable_water:', 10, -1, {'conceal':'🚱'})
call matchadd('Conceal', ':no_bicycles:', 10, -1, {'conceal':'🚳'})
call matchadd('Conceal', ':no_pedestrians:', 10, -1, {'conceal':'🚷'})
call matchadd('Conceal', ':children_crossing:', 10, -1, {'conceal':'🚸'})
call matchadd('Conceal', ':no_entry:', 10, -1, {'conceal':'⛔'})
" call matchadd('Conceal', ':eight_spoked_asterisk:', 10, -1, {'conceal':'✳️'})
" call matchadd('Conceal', ':eight_pointed_black_star:', 10, -1, {'conceal':'✴️'})
call matchadd('Conceal', ':heart_decoration:', 10, -1, {'conceal':'💟'})
call matchadd('Conceal', ':vs:', 10, -1, {'conceal':'🆚'})
call matchadd('Conceal', ':vibration_mode:', 10, -1, {'conceal':'📳'})
call matchadd('Conceal', ':mobile_phone_off:', 10, -1, {'conceal':'📴'})
call matchadd('Conceal', ':chart:', 10, -1, {'conceal':'💹'})
call matchadd('Conceal', ':currency_exchange:', 10, -1, {'conceal':'💱'})
call matchadd('Conceal', ':aries:', 10, -1, {'conceal':'♈'})
call matchadd('Conceal', ':taurus:', 10, -1, {'conceal':'♉'})
call matchadd('Conceal', ':gemini:', 10, -1, {'conceal':'♊'})
call matchadd('Conceal', ':cancer:', 10, -1, {'conceal':'♋'})
call matchadd('Conceal', ':leo:', 10, -1, {'conceal':'♌'})
call matchadd('Conceal', ':virgo:', 10, -1, {'conceal':'♍'})
call matchadd('Conceal', ':libra:', 10, -1, {'conceal':'♎'})
call matchadd('Conceal', ':scorpius:', 10, -1, {'conceal':'♏'})
call matchadd('Conceal', ':sagittarius:', 10, -1, {'conceal':'♐'})
call matchadd('Conceal', ':capricorn:', 10, -1, {'conceal':'♑'})
call matchadd('Conceal', ':aquarius:', 10, -1, {'conceal':'♒'})
call matchadd('Conceal', ':pisces:', 10, -1, {'conceal':'♓'})
call matchadd('Conceal', ':ophiuchus:', 10, -1, {'conceal':'⛎'})
call matchadd('Conceal', ':six_pointed_star:', 10, -1, {'conceal':'🔯'})
call matchadd('Conceal', ':negative_squared_cross_mark:', 10, -1, {'conceal':'❎'})
" call matchadd('Conceal', ':a:', 10, -1, {'conceal':'🅰️'})
" call matchadd('Conceal', ':b:', 10, -1, {'conceal':'🅱️'})
call matchadd('Conceal', ':ab:', 10, -1, {'conceal':'🆎'})
" call matchadd('Conceal', ':o2:', 10, -1, {'conceal':'🅾️'})
call matchadd('Conceal', ':diamond_shape_with_a_dot_inside:', 10, -1, {'conceal':'💠'})
" call matchadd('Conceal', ':recycle:', 10, -1, {'conceal':'♻️'})
call matchadd('Conceal', ':end:', 10, -1, {'conceal':'🔚'})
call matchadd('Conceal', ':on:', 10, -1, {'conceal':'🔛'})
call matchadd('Conceal', ':soon:', 10, -1, {'conceal':'🔜'})
call matchadd('Conceal', ':clock1:', 10, -1, {'conceal':'🕐'})
call matchadd('Conceal', ':clock130:', 10, -1, {'conceal':'🕜'})
call matchadd('Conceal', ':clock10:', 10, -1, {'conceal':'🕙'})
call matchadd('Conceal', ':clock1030:', 10, -1, {'conceal':'🕥'})
call matchadd('Conceal', ':clock11:', 10, -1, {'conceal':'🕚'})
call matchadd('Conceal', ':clock1130:', 10, -1, {'conceal':'🕦'})
call matchadd('Conceal', ':clock12:', 10, -1, {'conceal':'🕛'})
call matchadd('Conceal', ':clock1230:', 10, -1, {'conceal':'🕧'})
call matchadd('Conceal', ':clock2:', 10, -1, {'conceal':'🕑'})
call matchadd('Conceal', ':clock230:', 10, -1, {'conceal':'🕝'})
call matchadd('Conceal', ':clock3:', 10, -1, {'conceal':'🕒'})
call matchadd('Conceal', ':clock330:', 10, -1, {'conceal':'🕞'})
call matchadd('Conceal', ':clock4:', 10, -1, {'conceal':'🕓'})
call matchadd('Conceal', ':clock430:', 10, -1, {'conceal':'🕟'})
call matchadd('Conceal', ':clock5:', 10, -1, {'conceal':'🕔'})
call matchadd('Conceal', ':clock530:', 10, -1, {'conceal':'🕠'})
call matchadd('Conceal', ':clock6:', 10, -1, {'conceal':'🕕'})
call matchadd('Conceal', ':clock630:', 10, -1, {'conceal':'🕡'})
call matchadd('Conceal', ':clock7:', 10, -1, {'conceal':'🕖'})
call matchadd('Conceal', ':clock730:', 10, -1, {'conceal':'🕢'})
call matchadd('Conceal', ':clock8:', 10, -1, {'conceal':'🕗'})
call matchadd('Conceal', ':clock830:', 10, -1, {'conceal':'🕣'})
call matchadd('Conceal', ':clock9:', 10, -1, {'conceal':'🕘'})
call matchadd('Conceal', ':clock930:', 10, -1, {'conceal':'🕤'})
call matchadd('Conceal', ':heavy_dollar_sign:', 10, -1, {'conceal':'💲'})
" call matchadd('Conceal', ':copyright:', 10, -1, {'conceal':'©️'})
" call matchadd('Conceal', ':registered:', 10, -1, {'conceal':'®️'})
" call matchadd('Conceal', ':tm:', 10, -1, {'conceal':'™️'})
call matchadd('Conceal', ':x:', 10, -1, {'conceal':'❌'})
call matchadd('Conceal', ':heavy_exclamation_mark:', 10, -1, {'conceal':'❗'})
" call matchadd('Conceal', ':bangbang:', 10, -1, {'conceal':'‼️'})
" call matchadd('Conceal', ':interrobang:', 10, -1, {'conceal':'⁉️'})
call matchadd('Conceal', ':o:', 10, -1, {'conceal':'⭕'})
" call matchadd('Conceal', ':heavy_multiplication_x:', 10, -1, {'conceal':'✖️'})
call matchadd('Conceal', ':heavy_plus_sign:', 10, -1, {'conceal':'➕'})
call matchadd('Conceal', ':heavy_minus_sign:', 10, -1, {'conceal':'➖'})
call matchadd('Conceal', ':heavy_division_sign:', 10, -1, {'conceal':'➗'})
call matchadd('Conceal', ':white_flower:', 10, -1, {'conceal':'💮'})
call matchadd('Conceal', ':100:', 10, -1, {'conceal':'💯'})
" call matchadd('Conceal', ':heavy_check_mark:', 10, -1, {'conceal':'✔️'})
" call matchadd('Conceal', ':ballot_box_with_check:', 10, -1, {'conceal':'☑️'})
call matchadd('Conceal', ':radio_button:', 10, -1, {'conceal':'🔘'})
call matchadd('Conceal', ':link:', 10, -1, {'conceal':'🔗'})
call matchadd('Conceal', ':curly_loop:', 10, -1, {'conceal':'➰'})
" call matchadd('Conceal', ':wavy_dash:', 10, -1, {'conceal':'〰️'})
" call matchadd('Conceal', ':part_alternation_mark:', 10, -1, {'conceal':'〽️'})
call matchadd('Conceal', ':trident:', 10, -1, {'conceal':'🔱'})
" call matchadd('Conceal', ':black_square:', 10, -1, {'conceal':'⬛'})
" call matchadd('Conceal', ':white_square:', 10, -1, {'conceal':'⬜'})
call matchadd('Conceal', ':white_check_mark:', 10, -1, {'conceal':'✅'})
call matchadd('Conceal', ':black_square_button:', 10, -1, {'conceal':'🔲'})
call matchadd('Conceal', ':white_square_button:', 10, -1, {'conceal':'🔳'})
" call matchadd('Conceal', ':black_circle:', 10, -1, {'conceal':'⚫'})
" call matchadd('Conceal', ':white_circle:', 10, -1, {'conceal':'⚪'})
call matchadd('Conceal', ':red_circle:', 10, -1, {'conceal':'🔴'})
call matchadd('Conceal', ':large_blue_circle:', 10, -1, {'conceal':'🔵'})
call matchadd('Conceal', ':large_blue_diamond:', 10, -1, {'conceal':'🔷'})
call matchadd('Conceal', ':large_orange_diamond:', 10, -1, {'conceal':'🔶'})
call matchadd('Conceal', ':small_blue_diamond:', 10, -1, {'conceal':'🔹'})
call matchadd('Conceal', ':small_orange_diamond:', 10, -1, {'conceal':'🔸'})
call matchadd('Conceal', ':small_red_triangle:', 10, -1, {'conceal':'🔺'})
call matchadd('Conceal', ':small_red_triangle_down:', 10, -1, {'conceal':'🔻'})

let b:current_syntax = "octo"
if main_syntax ==# 'octo'
  unlet main_syntax
endif
