name: Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  x64-ubuntu:
    name: X64-ubuntu (${{ matrix.nvim_version }})
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        nvim_version: [stable, nightly]
    steps:
      - uses: actions/checkout@v6
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim_version }}
      - name: Restore plenary.nvim from cache
        uses: actions/cache@v5
        with:
          path: ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          key: ${{ runner.os }}-plenary-${{ matrix.nvim_version }}
      - name: Install plenary.nvim
        run: |
          mkdir -p ~/.local/share/nvim/site/pack/vendor/start
          test -d ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim || git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          ln -s $(pwd) ~/.local/share/nvim/site/pack/vendor/start
      - name: Run tests
        run: nvim --headless -c "PlenaryBustedDirectory lua/tests/plenary/ {minimal_init = 'lua/tests/minimal_init.vim'}"
